/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Box: typeof import('@element-plus/icons-vue')['Box']
  const Calendar: typeof import('@element-plus/icons-vue')['Calendar']
  const Check: typeof import('@element-plus/icons-vue')['Check']
  const Close: typeof import('@element-plus/icons-vue')['Close']
  const Connection: typeof import('@element-plus/icons-vue')['Connection']
  const DataAnalysis: typeof import('@element-plus/icons-vue')['DataAnalysis']
  const Delete: typeof import('@element-plus/icons-vue')['Delete']
  const Document: typeof import('@element-plus/icons-vue')['Document']
  const EditPen: typeof import('@element-plus/icons-vue')['EditPen']
  const Goods: typeof import('@element-plus/icons-vue')['Goods']
  const House: typeof import('@element-plus/icons-vue')['House']
  const OfficeBuilding: typeof import('@element-plus/icons-vue')['OfficeBuilding']
  const Plus: typeof import('@element-plus/icons-vue')['Plus']
  const Refresh: typeof import('@element-plus/icons-vue')['Refresh']
  const Search: typeof import('@element-plus/icons-vue')['Search']
  const Setting: typeof import('@element-plus/icons-vue')['Setting']
  const SwitchButton: typeof import('@element-plus/icons-vue')['SwitchButton']
  const Tickets: typeof import('@element-plus/icons-vue')['Tickets']
  const User: typeof import('@element-plus/icons-vue')['User']
  const UserFilled: typeof import('@element-plus/icons-vue')['UserFilled']
}
